export const COIN_FLIP_ADDRESS = '0x7E917915Cefc7f98d6d3cA07f21c4B950803D1dD' as const;

export const COIN_FLIP_ABI = [
  {
    inputs: [
      { internalType: 'address', name: '_entropyAddress', type: 'address' },
      { internalType: 'address', name: '_entropyProvider', type: 'address' },
      { internalType: 'uint256', name: '_minBet', type: 'uint256' },
      { internalType: 'uint256', name: '_maxBet', type: 'uint256' },
    ],
    stateMutability: 'payable',
    type: 'constructor',
  },
  {
    inputs: [
      { internalType: 'uint8', name: '_choice', type: 'uint8' },
      { internalType: 'bytes32', name: '_userRandomness', type: 'bytes32' },
    ],
    name: 'placeBet',
    outputs: [{ internalType: 'uint256', name: 'gameId', type: 'uint256' }],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_gameId', type: 'uint256' },
      { internalType: 'bytes32', name: '_providerRevelation', type: 'bytes32' },
    ],
    name: 'revealResult',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_gameId', type: 'uint256' }],
    name: 'cancelGame',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_player', type: 'address' }],
    name: 'getPlayerGames',
    outputs: [{ internalType: 'uint256[]', name: '', type: 'uint256[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_gameId', type: 'uint256' }],
    name: 'getGame',
    outputs: [
      {
        components: [
          { internalType: 'address', name: 'player', type: 'address' },
          { internalType: 'uint256', name: 'betAmount', type: 'uint256' },
          { internalType: 'uint8', name: 'playerChoice', type: 'uint8' },
          { internalType: 'uint8', name: 'result', type: 'uint8' },
          { internalType: 'bool', name: 'won', type: 'bool' },
          { internalType: 'uint256', name: 'payout', type: 'uint256' },
          { internalType: 'uint256', name: 'timestamp', type: 'uint256' },
          { internalType: 'enum CoinFlip.GameState', name: 'state', type: 'uint8' },
          { internalType: 'uint64', name: 'entropySequenceNumber', type: 'uint64' },
          { internalType: 'bytes32', name: 'userRandomness', type: 'bytes32' },
        ],
        internalType: 'struct CoinFlip.Game',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getEntropyFee',
    outputs: [{ internalType: 'uint128', name: '', type: 'uint128' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'minBet',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'maxBet',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'player', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' },
      { indexed: false, internalType: 'uint8', name: 'choice', type: 'uint8' },
      { indexed: false, internalType: 'uint256', name: 'gameId', type: 'uint256' },
      { indexed: false, internalType: 'uint64', name: 'sequenceNumber', type: 'uint64' },
      { indexed: false, internalType: 'bytes32', name: 'userCommitment', type: 'bytes32' },
    ],
    name: 'BetPlaced',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'player', type: 'address' },
      { indexed: true, internalType: 'uint256', name: 'gameId', type: 'uint256' },
      { indexed: false, internalType: 'uint8', name: 'choice', type: 'uint8' },
      { indexed: false, internalType: 'uint8', name: 'result', type: 'uint8' },
      { indexed: false, internalType: 'bool', name: 'won', type: 'bool' },
      { indexed: false, internalType: 'uint256', name: 'payout', type: 'uint256' },
    ],
    name: 'GameResult',
    type: 'event',
  },
] as const;
